/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecalculator;

/**
 *
 * @author Nighthawk
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputOutputTextfield = new javax.swing.JTextField();
        Buton7 = new javax.swing.JButton();
        Buton4 = new javax.swing.JButton();
        Buton1 = new javax.swing.JButton();
        ButonC = new javax.swing.JButton();
        Buton8 = new javax.swing.JButton();
        Buton5 = new javax.swing.JButton();
        Buton2 = new javax.swing.JButton();
        Buton0 = new javax.swing.JButton();
        Buton9 = new javax.swing.JButton();
        Buton6 = new javax.swing.JButton();
        Buton3 = new javax.swing.JButton();
        ButonDeci = new javax.swing.JButton();
        ButonDiv = new javax.swing.JButton();
        ButonMulti = new javax.swing.JButton();
        ButonAdd = new javax.swing.JButton();
        ButonSub = new javax.swing.JButton();
        ButonMs = new javax.swing.JButton();
        ButonMc = new javax.swing.JButton();
        ButonEqu = new javax.swing.JButton();
        ButonM = new javax.swing.JButton();
        ButonDel = new javax.swing.JButton();
        CalculatorMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputOutputTextfield.setText("0");
        InputOutputTextfield.setToolTipText("Input Numeric Value");

        Buton7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton7.setText("7");
        Buton7.setToolTipText("Imput 7");
        Buton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buton7ActionPerformed(evt);
            }
        });

        Buton4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton4.setText("4");
        Buton4.setToolTipText("Imput 4");

        Buton1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton1.setText("1");
        Buton1.setToolTipText("Imput 1");

        ButonC.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonC.setText("c");
        ButonC.setToolTipText("Clear Calculator");

        Buton8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton8.setText("8");
        Buton8.setToolTipText("Imput 8");

        Buton5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton5.setText("5");
        Buton5.setToolTipText("Imput 5");

        Buton2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton2.setText("2");
        Buton2.setToolTipText("Imput 2");

        Buton0.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton0.setText("0");
        Buton0.setToolTipText("Imput 0");

        Buton9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton9.setText("9");
        Buton9.setToolTipText("Imput 9");

        Buton6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton6.setText("6");
        Buton6.setToolTipText("Imput 6");

        Buton3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Buton3.setText("3");
        Buton3.setToolTipText("Imput 3");

        ButonDeci.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonDeci.setText(".");
        ButonDeci.setToolTipText("Imput Decimal");

        ButonDiv.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonDiv.setText("/");
        ButonDiv.setToolTipText("Division Operator");

        ButonMulti.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonMulti.setText("*");
        ButonMulti.setToolTipText("Multiplication Operator");

        ButonAdd.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonAdd.setText("+");
        ButonAdd.setToolTipText("Addition Operator");

        ButonSub.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonSub.setText("-");

        ButonMs.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonMs.setText("Ms");
        ButonMs.setToolTipText("Save Memorie Saved");

        ButonMc.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonMc.setText("Mc");
        ButonMc.setToolTipText("Delete Memorie");

        ButonEqu.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonEqu.setText("=");
        ButonEqu.setToolTipText("Equals Operator");

        ButonM.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonM.setText("M");
        ButonM.setToolTipText("Save Displayed Text as Memorie");

        ButonDel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButonDel.setText("Delete");
        ButonDel.setToolTipText("Imput Delete");

        FileMenu.setText("File");
        CalculatorMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        CalculatorMenuBar.add(EditMenu);

        HelpMenu.setText("Help");
        CalculatorMenuBar.add(HelpMenu);

        setJMenuBar(CalculatorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputOutputTextfield)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buton0, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Buton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButonC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Buton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButonDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Buton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButonMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButonDeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButonEqu)
                                    .addComponent(ButonAdd)
                                    .addComponent(ButonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButonM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButonMc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButonMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(ButonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputOutputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Buton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Buton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buton0, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Buton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Buton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ButonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ButonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButonMs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButonEqu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Buton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButonDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButonMc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButonM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Buton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buton0;
    private javax.swing.JButton Buton1;
    private javax.swing.JButton Buton2;
    private javax.swing.JButton Buton3;
    private javax.swing.JButton Buton4;
    private javax.swing.JButton Buton5;
    private javax.swing.JButton Buton6;
    private javax.swing.JButton Buton7;
    private javax.swing.JButton Buton8;
    private javax.swing.JButton Buton9;
    private javax.swing.JButton ButonAdd;
    private javax.swing.JButton ButonC;
    private javax.swing.JButton ButonDeci;
    private javax.swing.JButton ButonDel;
    private javax.swing.JButton ButonDiv;
    private javax.swing.JButton ButonEqu;
    private javax.swing.JButton ButonM;
    private javax.swing.JButton ButonMc;
    private javax.swing.JButton ButonMs;
    private javax.swing.JButton ButonMulti;
    private javax.swing.JButton ButonSub;
    private javax.swing.JMenuBar CalculatorMenuBar;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JTextField InputOutputTextfield;
    // End of variables declaration//GEN-END:variables
}
